### PR TITLE
Improve usage of the args

### PR DESCRIPTION
**Pull request by heldersepu**
Allow minification of single file or a list of files
Same for folders, now we can specify multiple folders

This fixes Issue #29

### CODE REVIEW

**Comment by heldersepu** [comment]
@deanhume Any chance of merging this PR soon ?

**Comment by rposbo** [comment]
@heldersepu I appreciate I've already merged this PR, but could you update the README to reflect your change as well? Thanks!

**Comment by heldersepu** [comment]
Sure what do you have in mind?
add a couple of samples showing how to minify a single file or a list of files...

**Comment by rposbo** [comment]
yep, exactly that; the README is currently folders-only, so pointing out you can now use it for single files with an example or two would be great

**Comment by heldersepu** [comment]
Done see PR #39

**Pull request merged**
